import type { ChartTheme } from './types';

export const THEME_PRESETS: Record<string, ChartTheme> = {
    'midnight-abyss': {
        id: 'midnight-abyss',
        name: 'Midnight Abyss',
        isDark: true,
        background: '#0B0C10',
        panelBackground: '#13161C',
        gridLines: '#1F2833',
        axisText: '#C5C6C7',
        crosshair: '#00F5D4',
        bullBody: '#00F5D4',
        bearBody: '#8338EC',
        bullWick: '#00F5D4',
        bearWick: '#8338EC',
        bullBorder: '#00F5D4',
        bearBorder: '#8338EC',
        accentColor: '#3A86C8',
        accentSource: 'bull'
    },
    'cyberpunk-neon': {
        id: 'cyberpunk-neon',
        name: 'Cyberpunk Neon',
        isDark: true,
        background: '#0D0E15',
        panelBackground: '#161824',
        gridLines: '#1A1C29',
        axisText: '#8E94AB',
        crosshair: '#00F0FF',
        bullBody: '#00F0FF',
        bearBody: '#FF007A',
        bullWick: '#00F0FF',
        bearWick: '#FF007A',
        bullBorder: '#00F0FF',
        bearBorder: '#FF007A',
        accentColor: '#00F0FF',
        accentSource: 'bull'
    },
    'crimson-pulse': {
        id: 'crimson-pulse',
        name: 'Crimson Pulse',
        isDark: false,
        background: '#F8F9FA',
        panelBackground: '#E9ECEF',
        gridLines: '#E9ECEF',
        axisText: '#2B2D42',
        crosshair: '#D90429',
        bullBody: '#2B2D42',
        bearBody: '#D90429',
        bullWick: '#2B2D42',
        bearWick: '#D90429',
        bullBorder: '#2B2D42',
        bearBorder: '#D90429',
        accentColor: '#EF233C',
        accentSource: 'custom'
    },
    'sunset-blaze': {
        id: 'sunset-blaze',
        name: 'Sunset Blaze',
        isDark: false,
        background: '#FFFDF9',
        panelBackground: '#F4EFE6',
        gridLines: '#F0EAE1',
        axisText: '#003049',
        crosshair: '#F77F00',
        bullBody: '#003049',
        bearBody: '#F77F00',
        bullWick: '#003049',
        bearWick: '#F77F00',
        bullBorder: '#003049',
        bearBorder: '#F77F00',
        accentColor: '#FCBF49',
        accentSource: 'custom'
    },
    'solar-spark': {
        id: 'solar-spark',
        name: 'Solar Spark',
        isDark: false,
        background: '#F8FAFC',
        panelBackground: '#E2E8F0',
        gridLines: '#ECEFF1',
        axisText: '#475569',
        crosshair: '#FFB703',
        bullBody: '#06D6A0',
        bearBody: '#FFB703',
        bullWick: '#06D6A0',
        bearWick: '#FFB703',
        bullBorder: '#06D6A0',
        bearBorder: '#FFB703',
        accentColor: '#FFD166',
        accentSource: 'bull'
    },
    'emerald-oasis': {
        id: 'emerald-oasis',
        name: 'Emerald Oasis',
        isDark: false,
        background: '#F4F9F6',
        panelBackground: '#E1EBE5',
        gridLines: '#E0EBE4',
        axisText: '#073B4C',
        crosshair: '#06D6A0',
        bullBody: '#06D6A0',
        bearBody: '#EF476F',
        bullWick: '#06D6A0',
        bearWick: '#EF476F',
        bullBorder: '#06D6A0',
        bearBorder: '#EF476F',
        accentColor: '#118AB2',
        accentSource: 'bull'
    },
    'hydro-tech': {
        id: 'hydro-tech',
        name: 'Hydro Tech',
        isDark: false,
        background: '#FAFCFF',
        panelBackground: '#E6EFF8',
        gridLines: '#E5ECF6',
        axisText: '#1E3A8A',
        crosshair: '#118AB2',
        bullBody: '#118AB2',
        bearBody: '#FF9F1C',
        bullWick: '#118AB2',
        bearWick: '#FF9F1C',
        bullBorder: '#118AB2',
        bearBorder: '#FF9F1C',
        accentColor: '#4EA8DE',
        accentSource: 'bull'
    },
    'amethyst-mystique': {
        id: 'amethyst-mystique',
        name: 'Amethyst Mystique',
        isDark: true,
        background: '#1E1B29',
        panelBackground: '#262235',
        gridLines: '#2C273D',
        axisText: '#C4B5FD',
        crosshair: '#FF006E',
        bullBody: '#3A86C8',
        bearBody: '#FF006E',
        bullWick: '#3A86C8',
        bearWick: '#FF006E',
        bullBorder: '#3A86C8',
        bearBorder: '#FF006E',
        accentColor: '#8338EC',
        accentSource: 'custom'
    },
    'corporate-trust': {
        id: 'corporate-trust',
        name: 'Corporate Trust',
        isDark: false,
        background: '#F8F9FA',
        panelBackground: '#E4E8EC',
        gridLines: '#E3E8EE',
        axisText: '#0F4C81',
        crosshair: '#1F78B4',
        bullBody: '#1F78B4',
        bearBody: '#E31A1C',
        bullWick: '#1F78B4',
        bearWick: '#E31A1C',
        bullBorder: '#1F78B4',
        bearBorder: '#E31A1C',
        accentColor: '#FFC107',
        accentSource: 'custom'
    },
    'matcha-mint': {
        id: 'matcha-mint',
        name: 'Matcha & Mint',
        isDark: false,
        background: '#F4F7F4',
        panelBackground: '#E3EAE3',
        gridLines: '#DFE5DF',
        axisText: '#2D5A27',
        crosshair: '#8FBC8F',
        bullBody: '#2D5A27',
        bearBody: '#C0392B',
        bullWick: '#2D5A27',
        bearWick: '#C0392B',
        bullBorder: '#2D5A27',
        bearBorder: '#C0392B',
        accentColor: '#8FBC8F',
        accentSource: 'bull'
    },
    'minimalist-mono': {
        id: 'minimalist-mono',
        name: 'Minimalist Monochrome',
        isDark: true,
        background: '#111111',
        panelBackground: '#1A1A1A',
        gridLines: '#262626',
        axisText: '#E5E5E5',
        crosshair: '#FFFFFF',
        bullBody: '#FFFFFF',
        bearBody: '#444444',
        bullWick: '#FFFFFF',
        bearWick: '#444444',
        bullBorder: '#FFFFFF',
        bearBorder: '#444444',
        accentColor: '#7F7F7F',
        accentSource: 'bull'
    },
    'bubblegum-pop': {
        id: 'bubblegum-pop',
        name: 'Bubblegum Pop',
        isDark: false,
        background: '#FFF0F5',
        panelBackground: '#F7DFE8',
        gridLines: '#EAD5DC',
        axisText: '#4A5568',
        crosshair: '#FFB7B2',
        bullBody: '#B5EAD7',
        bearBody: '#FFB7B2',
        bullWick: '#7BCBB2',
        bearWick: '#FF8E87',
        bullBorder: '#7BCBB2',
        bearBorder: '#FF8E87',
        accentColor: '#FFDAC1',
        accentSource: 'custom'
    },
    'sunset-horizon': {
        id: 'sunset-horizon',
        name: 'Sunset Horizon',
        isDark: false,
        background: '#FFFDF9',
        panelBackground: '#F7EDE6',
        gridLines: '#F2EAE1',
        axisText: '#4A154B',
        crosshair: '#E65C00',
        bullBody: '#E65C00',
        bearBody: '#4A154B',
        bullWick: '#E65C00',
        bearWick: '#4A154B',
        bullBorder: '#E65C00',
        bearBorder: '#4A154B',
        accentColor: '#F9D423',
        accentSource: 'custom'
    },
    'mystic-lavender': {
        id: 'mystic-lavender',
        name: 'Mystic Lavender',
        isDark: true,
        background: '#181824',
        panelBackground: '#222233',
        gridLines: '#28283C',
        axisText: '#A29BFE',
        crosshair: '#00CEC9',
        bullBody: '#00CEC9',
        bearBody: '#6C5CE7',
        bullWick: '#00CEC9',
        bearWick: '#6C5CE7',
        bullBorder: '#00CEC9',
        bearBorder: '#6C5CE7',
        accentColor: '#A29BFE',
        accentSource: 'bull'
    }
};